# Generated by Django 5.0.6 on 2024-05-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
