# Generated by Django 5.0.6 on 2024-05-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='uploads'),
        ),
    ]
